### PR TITLE
Port EPAM's VR fork to PyMOL 2.4

### PR DESCRIPTION
**Pull request by speleo3**
Porting the essential parts of EPAM System's "openvr" branch to the master branch.

Original authors:
Natalia Smirnova, EPAM Systems, Inc.
Pavel Smirnov, EPAM Systems, Inc.
Paul Smirnov, EPAM Systems, Inc.

Original fork:
https://github.com/epam/pymol-open-source/tree/openvr

Adjustments:
- Make feature optional with `--openvr` compile option
- Python 3 support
- Remove C++11 workarounds
- Exclude build system changes

### CODE REVIEW

**Comment by paulsmirnov** [comment]
It's nice that you have found our work useful and have spent time finalizing our code! 🎉

Would you mind a few minor corrections/notes while we are browsing through the code?
- Paul = Pavel, it is just a different spelling, so you can remove the "third" author mention,
- Would you consider keeping an attribution by using [`Co-authored-by`](https://help.github.com/en/github/committing-changes-to-your-project/creating-a-commit-with-multiple-authors) tag in the commit? It is not required due to MIT license but will make us even happier than we already are 😄 

Thanks again for your efforts!

**Comment by speleo3** [comment]
Thanks @paulsmirnov for your comments! I've added the Co-authored-by tags and corrected the author list.

**Comment by malperovich** [comment]
Hi @speleo3 , many thanks for your interest and responding to @paulsmirnov 's comments.
I'm happy to confirm we are OK with this merge

**Comment by speleo3** [comment]
Thanks @malperovich for confirming!

**Pull request merged**
