### PR TITLE
Nucleic Acid builder and general improvements

### PR DESCRIPTION
**Pull request by JarrettSJohnson**
Addresses #102 #351 

Migrating support from Incentive for the following:

- Nucleic Acid builder in the Builder panel (Jarrett Johnson @JarrettSJohnson)
- `fnab` command to build nucleic acid chains by sequence (Jarrett Johnson @JarrettSJohnson)
- Improvements to nucleic acid building from native structures (Thomas Stewart @TstewDev)
- highlight attachment points for improved usability (Thomas Holder @speleo3)

Co-authored-by: Jarrett Johnson <jarrett.johnson@schrodinger.com>
Co-authored-by: Thomas Stewart <thomas.stewart@schrodinger.com>
Co-authored-by: Thomas Holder <thomas@thomas-holder.de>

### CODE REVIEW

**Comment by JarrettSJohnson** [comment]
Requesting reviews from co-authors: @TstewDev @speleo3

**Review by TstewDev — APPROVED** [review]
I agree with the point that there is a lot to be done here with regard to refactoring and improving readability (looking at you `editor.py`). However, for now I think this is everything we need to add this feature to open-source. We should file a ticket on the incentive side of things to get this cleaned up and then merge those changes in later on.

**Comment by speleo3** [comment]
I also agree, first sync with open-source, then refactor.

But before jumping to refactoring: Are there any tests? There are none in this pull request.

**Comment by JarrettSJohnson** [comment]
> I also agree, first sync with open-source, then refactor.
> 
> But before jumping to refactoring: Are there any tests? There are none in this pull request.

Removed the incentive requirement. All previous tests (which included 'fnab') for this module were brought over during the pymol-testing migration.

**Review by speleo3 — APPROVED** [review]

**Pull request merged**
